/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pc
 */
public class board extends javax.swing.JFrame {

    /**
     * Creates new form board
     */
    public board() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        Go1 = new javax.swing.JLabel();
        CrapperStreet2 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        GangstersParadise4 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        BrightonStation6 = new javax.swing.JLabel();
        WeepingAngel7 = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        PottsAvenue9 = new javax.swing.JLabel();
        NardoleDrive10 = new javax.swing.JLabel();
        Jail11 = new javax.swing.JLabel();
        SkywalkerDrive12 = new javax.swing.JLabel();
        TeslaPowerCo13 = new javax.swing.JLabel();
        WookieHole14 = new javax.swing.JLabel();
        ReyLane15 = new javax.swing.JLabel();
        HoveStation16 = new javax.swing.JLabel();
        CooperDrive17 = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        WolowitzStreet19 = new javax.swing.JLabel();
        PennyLane20 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        YueFeiSquare22 = new javax.swing.JLabel();
        jLabel132 = new javax.swing.JLabel();
        MulanRouge24 = new javax.swing.JLabel();
        HanXinGarden25 = new javax.swing.JLabel();
        FalmerStation26 = new javax.swing.JLabel();
        KirkClose27 = new javax.swing.JLabel();
        PicardAvenue28 = new javax.swing.JLabel();
        EdisonWater29 = new javax.swing.JLabel();
        CrusherCreek30 = new javax.swing.JLabel();
        jLabel140 = new javax.swing.JLabel();
        SiratMews32 = new javax.swing.JLabel();
        GhengisCrescent33 = new javax.swing.JLabel();
        jLabel143 = new javax.swing.JLabel();
        IbisClose35 = new javax.swing.JLabel();
        LewesStation36 = new javax.swing.JLabel();
        jLabel146 = new javax.swing.JLabel();
        HawkingWay38 = new javax.swing.JLabel();
        jLabel148 = new javax.swing.JLabel();
        TuringHeights40 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Go1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/Go.png"))); // NOI18N
        Go1.setMaximumSize(new java.awt.Dimension(100, 100));
        Go1.setMinimumSize(new java.awt.Dimension(100, 100));
        Go1.setPreferredSize(new java.awt.Dimension(100, 100));

        CrapperStreet2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/Crapper Street.png"))); // NOI18N
        CrapperStreet2.setMaximumSize(new java.awt.Dimension(100, 100));
        CrapperStreet2.setMinimumSize(new java.awt.Dimension(100, 100));
        CrapperStreet2.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel112.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/emptyset.png"))); // NOI18N
        jLabel112.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel112.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel112.setPreferredSize(new java.awt.Dimension(100, 100));

        GangstersParadise4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/Gangsters Paradise.png"))); // NOI18N
        GangstersParadise4.setMaximumSize(new java.awt.Dimension(100, 100));
        GangstersParadise4.setMinimumSize(new java.awt.Dimension(100, 100));
        GangstersParadise4.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel114.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/emptyset.png"))); // NOI18N
        jLabel114.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel114.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel114.setPreferredSize(new java.awt.Dimension(100, 100));

        BrightonStation6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/Brighon Station.png"))); // NOI18N
        BrightonStation6.setMaximumSize(new java.awt.Dimension(100, 100));
        BrightonStation6.setMinimumSize(new java.awt.Dimension(100, 100));
        BrightonStation6.setPreferredSize(new java.awt.Dimension(100, 100));

        WeepingAngel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/Weeping Angel.png"))); // NOI18N
        WeepingAngel7.setMaximumSize(new java.awt.Dimension(100, 100));
        WeepingAngel7.setMinimumSize(new java.awt.Dimension(100, 100));
        WeepingAngel7.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel117.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/emptyset.png"))); // NOI18N
        jLabel117.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel117.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel117.setPreferredSize(new java.awt.Dimension(100, 100));

        PottsAvenue9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/Potts Avenue.png"))); // NOI18N
        PottsAvenue9.setMaximumSize(new java.awt.Dimension(100, 100));
        PottsAvenue9.setMinimumSize(new java.awt.Dimension(100, 100));
        PottsAvenue9.setPreferredSize(new java.awt.Dimension(100, 100));

        NardoleDrive10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/Nadole Drive.png"))); // NOI18N
        NardoleDrive10.setMaximumSize(new java.awt.Dimension(100, 100));
        NardoleDrive10.setMinimumSize(new java.awt.Dimension(100, 100));
        NardoleDrive10.setPreferredSize(new java.awt.Dimension(100, 100));

        Jail11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/Jail.png"))); // NOI18N
        Jail11.setMaximumSize(new java.awt.Dimension(100, 100));
        Jail11.setMinimumSize(new java.awt.Dimension(100, 100));
        Jail11.setPreferredSize(new java.awt.Dimension(100, 100));

        SkywalkerDrive12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/Skywalker Drive.png"))); // NOI18N
        SkywalkerDrive12.setMaximumSize(new java.awt.Dimension(100, 100));
        SkywalkerDrive12.setMinimumSize(new java.awt.Dimension(100, 100));
        SkywalkerDrive12.setPreferredSize(new java.awt.Dimension(100, 100));

        TeslaPowerCo13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/Tesla Power Co.png"))); // NOI18N
        TeslaPowerCo13.setMaximumSize(new java.awt.Dimension(100, 100));
        TeslaPowerCo13.setMinimumSize(new java.awt.Dimension(100, 100));
        TeslaPowerCo13.setPreferredSize(new java.awt.Dimension(100, 100));

        WookieHole14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/Wookie Hole.png"))); // NOI18N
        WookieHole14.setMaximumSize(new java.awt.Dimension(100, 100));
        WookieHole14.setMinimumSize(new java.awt.Dimension(100, 100));
        WookieHole14.setPreferredSize(new java.awt.Dimension(100, 100));

        ReyLane15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/Rey Lane.png"))); // NOI18N
        ReyLane15.setMaximumSize(new java.awt.Dimension(100, 100));
        ReyLane15.setMinimumSize(new java.awt.Dimension(100, 100));
        ReyLane15.setPreferredSize(new java.awt.Dimension(100, 100));

        HoveStation16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/Hove Station.jpg"))); // NOI18N
        HoveStation16.setMaximumSize(new java.awt.Dimension(100, 100));
        HoveStation16.setMinimumSize(new java.awt.Dimension(100, 100));
        HoveStation16.setPreferredSize(new java.awt.Dimension(100, 100));

        CooperDrive17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/Cooper Drive.png"))); // NOI18N
        CooperDrive17.setMaximumSize(new java.awt.Dimension(100, 100));
        CooperDrive17.setMinimumSize(new java.awt.Dimension(100, 100));
        CooperDrive17.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel127.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/emptyset.png"))); // NOI18N
        jLabel127.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel127.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel127.setPreferredSize(new java.awt.Dimension(100, 100));

        WolowitzStreet19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/Wolowitz Street.png"))); // NOI18N
        WolowitzStreet19.setMaximumSize(new java.awt.Dimension(100, 100));
        WolowitzStreet19.setMinimumSize(new java.awt.Dimension(100, 100));
        WolowitzStreet19.setPreferredSize(new java.awt.Dimension(100, 100));

        PennyLane20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/Penny Lane.png"))); // NOI18N
        PennyLane20.setMaximumSize(new java.awt.Dimension(100, 100));
        PennyLane20.setMinimumSize(new java.awt.Dimension(100, 100));
        PennyLane20.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel130.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/emptyset.png"))); // NOI18N
        jLabel130.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel130.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel130.setPreferredSize(new java.awt.Dimension(100, 100));

        YueFeiSquare22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/Yue Fei Square.png"))); // NOI18N
        YueFeiSquare22.setMaximumSize(new java.awt.Dimension(100, 100));
        YueFeiSquare22.setMinimumSize(new java.awt.Dimension(100, 100));
        YueFeiSquare22.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel132.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/emptyset.png"))); // NOI18N
        jLabel132.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel132.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel132.setPreferredSize(new java.awt.Dimension(100, 100));

        MulanRouge24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/Mulan Rouge.png"))); // NOI18N
        MulanRouge24.setMaximumSize(new java.awt.Dimension(100, 100));
        MulanRouge24.setMinimumSize(new java.awt.Dimension(100, 100));
        MulanRouge24.setPreferredSize(new java.awt.Dimension(100, 100));

        HanXinGarden25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/Han Xin Gardens.png"))); // NOI18N
        HanXinGarden25.setMaximumSize(new java.awt.Dimension(100, 100));
        HanXinGarden25.setMinimumSize(new java.awt.Dimension(100, 100));
        HanXinGarden25.setPreferredSize(new java.awt.Dimension(100, 100));

        FalmerStation26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/Falmer Station.png"))); // NOI18N
        FalmerStation26.setMaximumSize(new java.awt.Dimension(100, 100));
        FalmerStation26.setMinimumSize(new java.awt.Dimension(100, 100));
        FalmerStation26.setPreferredSize(new java.awt.Dimension(100, 100));

        KirkClose27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/Kirk Close.png"))); // NOI18N
        KirkClose27.setMaximumSize(new java.awt.Dimension(100, 100));
        KirkClose27.setMinimumSize(new java.awt.Dimension(100, 100));
        KirkClose27.setPreferredSize(new java.awt.Dimension(100, 100));

        PicardAvenue28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/Picard Avenue.png"))); // NOI18N
        PicardAvenue28.setMaximumSize(new java.awt.Dimension(100, 100));
        PicardAvenue28.setMinimumSize(new java.awt.Dimension(100, 100));
        PicardAvenue28.setPreferredSize(new java.awt.Dimension(100, 100));

        EdisonWater29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/Edison Water.png"))); // NOI18N
        EdisonWater29.setMaximumSize(new java.awt.Dimension(100, 100));
        EdisonWater29.setMinimumSize(new java.awt.Dimension(100, 100));
        EdisonWater29.setPreferredSize(new java.awt.Dimension(100, 100));

        CrusherCreek30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/Crusher Creek.png"))); // NOI18N
        CrusherCreek30.setMaximumSize(new java.awt.Dimension(100, 100));
        CrusherCreek30.setMinimumSize(new java.awt.Dimension(100, 100));
        CrusherCreek30.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel140.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/emptyset.png"))); // NOI18N
        jLabel140.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel140.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel140.setPreferredSize(new java.awt.Dimension(100, 100));

        SiratMews32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/Sirat Mews.png"))); // NOI18N
        SiratMews32.setMaximumSize(new java.awt.Dimension(100, 100));
        SiratMews32.setMinimumSize(new java.awt.Dimension(100, 100));
        SiratMews32.setPreferredSize(new java.awt.Dimension(100, 100));

        GhengisCrescent33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/Ghengis Crescent.png"))); // NOI18N
        GhengisCrescent33.setMaximumSize(new java.awt.Dimension(100, 100));
        GhengisCrescent33.setMinimumSize(new java.awt.Dimension(100, 100));
        GhengisCrescent33.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel143.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/emptyset.png"))); // NOI18N
        jLabel143.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel143.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel143.setPreferredSize(new java.awt.Dimension(100, 100));

        IbisClose35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/Ibis Close.png"))); // NOI18N
        IbisClose35.setMaximumSize(new java.awt.Dimension(100, 100));
        IbisClose35.setMinimumSize(new java.awt.Dimension(100, 100));
        IbisClose35.setPreferredSize(new java.awt.Dimension(100, 100));

        LewesStation36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/Lewes Station.png"))); // NOI18N
        LewesStation36.setMaximumSize(new java.awt.Dimension(100, 100));
        LewesStation36.setMinimumSize(new java.awt.Dimension(100, 100));
        LewesStation36.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel146.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/emptyset.png"))); // NOI18N
        jLabel146.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel146.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel146.setPreferredSize(new java.awt.Dimension(100, 100));

        HawkingWay38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/Hawking.png"))); // NOI18N
        HawkingWay38.setMaximumSize(new java.awt.Dimension(100, 100));
        HawkingWay38.setMinimumSize(new java.awt.Dimension(100, 100));
        HawkingWay38.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel148.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/emptyset.png"))); // NOI18N
        jLabel148.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel148.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel148.setPreferredSize(new java.awt.Dimension(100, 100));

        TuringHeights40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Watson/images/Turing Heights.png"))); // NOI18N
        TuringHeights40.setMaximumSize(new java.awt.Dimension(100, 100));
        TuringHeights40.setMinimumSize(new java.awt.Dimension(100, 100));
        TuringHeights40.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29))
                                .addGap(0, 0, 0)
                                .addComponent(jLabel6))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel34)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel10)))))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel5)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel4)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel36)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel12)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel13)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel35)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel14))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel27)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel7)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel26)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel25)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel3)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel24)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel2))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel16)
                        .addComponent(jLabel32)
                        .addComponent(jLabel17)
                        .addComponent(jLabel15)
                        .addComponent(jLabel33)))
                .addGap(302, 302, 302)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel31))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel22)
                                .addComponent(jLabel23)
                                .addComponent(jLabel39)
                                .addComponent(jLabel21)
                                .addComponent(jLabel41))
                            .addComponent(jLabel40))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(345, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel127, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CooperDrive17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HoveStation16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReyLane15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WookieHole14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TeslaPowerCo13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jail11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SkywalkerDrive12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WolowitzStreet19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PennyLane20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel130, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(YueFeiSquare22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel132, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(MulanRouge24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(HanXinGarden25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(FalmerStation26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(KirkClose27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(PicardAvenue28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(EdisonWater29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CrusherCreek30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel140, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LewesStation36, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SiratMews32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GhengisCrescent33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel143, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IbisClose35, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(HawkingWay38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel146, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NardoleDrive10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(PottsAvenue9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel117, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(WeepingAngel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(BrightonStation6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel114, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(GangstersParadise4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel112, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(CrapperStreet2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TuringHeights40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Go1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel148, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, 0)))
                .addContainerGap(303, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SiratMews32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(GhengisCrescent33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel132, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MulanRouge24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HanXinGarden25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FalmerStation26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(KirkClose27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PicardAvenue28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EdisonWater29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CrusherCreek30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel140, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(YueFeiSquare22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(100, 100, 100))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel130, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(PennyLane20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0)
                        .addComponent(WolowitzStreet19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel127, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel143, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CooperDrive17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IbisClose35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HoveStation16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LewesStation36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReyLane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel146, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WookieHole14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HawkingWay38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(TeslaPowerCo13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel148, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(TuringHeights40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Go1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CrapperStreet2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel112, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GangstersParadise4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel114, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BrightonStation6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WeepingAngel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel117, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PottsAvenue9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NardoleDrive10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(SkywalkerDrive12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Jail11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel33)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel30))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(2, 2, 2)))
                                .addComponent(jLabel36)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13))
                            .addComponent(jLabel14)
                            .addComponent(jLabel35)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel31)))
                        .addComponent(jLabel15))
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel38)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel32)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel16)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel41)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel21)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel39)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel22)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel11)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel10)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel29)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel9)
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel24)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel25)
                                .addComponent(jLabel26)
                                .addComponent(jLabel7)
                                .addComponent(jLabel27)
                                .addComponent(jLabel8)
                                .addComponent(jLabel6)
                                .addComponent(jLabel28)))))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new board().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BrightonStation6;
    private javax.swing.JLabel CooperDrive17;
    private javax.swing.JLabel CrapperStreet2;
    private javax.swing.JLabel CrusherCreek30;
    private javax.swing.JLabel EdisonWater29;
    private javax.swing.JLabel FalmerStation26;
    private javax.swing.JLabel GangstersParadise4;
    private javax.swing.JLabel GhengisCrescent33;
    private javax.swing.JLabel Go1;
    private javax.swing.JLabel HanXinGarden25;
    private javax.swing.JLabel HawkingWay38;
    private javax.swing.JLabel HoveStation16;
    private javax.swing.JLabel IbisClose35;
    private javax.swing.JLabel Jail11;
    private javax.swing.JLabel KirkClose27;
    private javax.swing.JLabel LewesStation36;
    private javax.swing.JLabel MulanRouge24;
    private javax.swing.JLabel NardoleDrive10;
    private javax.swing.JLabel PennyLane20;
    private javax.swing.JLabel PicardAvenue28;
    private javax.swing.JLabel PottsAvenue9;
    private javax.swing.JLabel ReyLane15;
    private javax.swing.JLabel SiratMews32;
    private javax.swing.JLabel SkywalkerDrive12;
    private javax.swing.JLabel TeslaPowerCo13;
    private javax.swing.JLabel TuringHeights40;
    private javax.swing.JLabel WeepingAngel7;
    private javax.swing.JLabel WolowitzStreet19;
    private javax.swing.JLabel WookieHole14;
    private javax.swing.JLabel YueFeiSquare22;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
